<a href="https://colab.research.google.com/github/Kamill99/Data_Science/blob/main/Numpy/numpy_indices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
A = np.arange(20)

In [ ]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A[3]

3

In [ ]:
A[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
A[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
A = A.reshape(4, 5)

In [ ]:
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
A[:, 1]

array([ 1,  6, 11, 16])

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[1, 1]

6

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [4]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
A = A.reshape(3, -1)

In [7]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [10]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]


In [11]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [12]:
A.shape

(3, 5)

In [13]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
A.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [15]:
A > 5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
A[A > 3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
A[np.bitwise_and(A > 2, A < 9)]

array([3, 4, 5, 6, 7, 8])