<a href="https://colab.research.google.com/github/Kamill99/Data_Science/blob/main/Numpy/numpy_indices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.arange(20)

In [3]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
A[3]

3

In [5]:
A[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
A[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
A = A.reshape(4, 5)

In [10]:
A[0]

array([0, 1, 2, 3, 4])

In [13]:
A[:, 1]

array([ 1,  6, 11, 16])

In [14]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
A[1, 1]

6

In [17]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])