<a href="https://colab.research.google.com/github/Kamill99/Data_Science/blob/main/Numpy/numpy_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Norma wektora, długość

In [4]:
v1 = np.array([-2, 4])

In [5]:
np.linalg.norm(v1)

4.47213595499958

In [6]:
v2 = np.array([-10, 10, 13])

Norma euklidesowa

In [7]:
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [8]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

Odległość dwóch punktów w przestzeni

In [9]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

Mnożenie macierzy

In [11]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [12]:
Z = np.dot(X, Y)

In [13]:
Z

array([[ 2],
       [-6]])

In [14]:
Z.shape

(2, 1)

Wyznacznik macierzy

In [15]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

In [16]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

Ślad macierzy

In [17]:
A

array([[ 2,  4],
       [-1,  3]])

In [18]:
np.trace(A)

5

Macierz jednostkowa

In [19]:
np.eye(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [20]:
A

array([[ 2,  4],
       [-1,  3]])

In [21]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [22]:
np.dot(A, B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [23]:
np.set_printoptions(precision=4, suppress=True)

In [24]:
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [25]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [26]:
A

array([[ 2,  4],
       [-1,  3]])

In [27]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [28]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [29]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [31]:
B = np.array([[10],[-1]])

In [33]:
print(B)

[[10]
 [-1]]


In [34]:
A_inv = np.linalg.inv(A)

In [35]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [36]:
X.shape

(2, 1)