<a href="https://colab.research.google.com/github/Kamill99/Data_Science/blob/main/Numpy/numpy_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.randn()

0.48634537257997473

In [3]:
np.random.randn(5)

array([ 1.59440842,  0.10678221, -0.1917992 ,  0.91861412, -0.86103116])

In [4]:
np.random.randn(5,4)

array([[ 0.49772822, -1.78231474, -1.34768135,  0.13282145],
       [ 0.87181685,  0.84742515, -0.35670057,  0.79048759],
       [ 0.62879382, -1.97708131,  0.03313685, -1.91712921],
       [ 0.38790988, -1.26501381, -0.17354661,  0.32112508],
       [ 0.2794125 , -2.38601349,  0.7970518 ,  0.7863423 ]])

In [5]:
np.random.rand()

0.3945190387197859

In [7]:
np.random.randint(10)

5

In [9]:
np.random.randint(low=10, high=50,size=5)

array([17, 20, 39, 29, 11])

In [10]:
np.random.choice([1, 2, 3, 4, 5])

1

In [11]:
data = np.arange(10)

In [12]:
print(data)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.random.shuffle(data)

In [15]:
data

array([6, 7, 5, 2, 1, 0, 9, 8, 3, 4])