<a href="https://colab.research.google.com/github/Kamill99/Data_Science/blob/main/numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.4'

In [ ]:
help(np.array)

In [4]:
x = np.array([2, 4])
x

array([2, 4])

In [5]:
x.ndim

1

In [6]:
x.shape

(2,)

In [7]:
x.size

2

In [8]:
x.dtype

dtype('int64')

In [11]:
x = np.array([3.2, 4.2, 6.7])
print(x)

[3.2 4.2 6.7]


In [12]:
x.dtype

dtype('float64')

In [15]:
x = np.array([[1, 5], [6, 4]])

In [16]:
x.shape

(2, 2)

In [18]:
x = np.array([[1, 2, 5], [8, 1, 5]])
print(x)

[[1 2 5]
 [8 1 5]]


In [19]:
x.shape

(2, 3)

In [27]:
x = np.array(
    [[[3, 1, 8],
     [3, 2, 5]],

     [[6, 8, 1],
      [4, 3, 2]]]
    )
x

array([[[3, 1, 8],
        [3, 2, 5]],

       [[6, 8, 1],
        [4, 3, 2]]])

In [28]:
x.ndim

3

In [29]:
x.shape

(2, 2, 3)