<a href="https://colab.research.google.com/github/Kamill99/Data_Science/blob/main/Numpy/numpy_arrays_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([1, 5, 3, 8])
B = np.array([4, 2, 1, -3])
print(A)
print(B)

[1 5 3 8]
[ 4  2  1 -3]


In [ ]:
A + B

array([5, 7, 4, 5])

In [ ]:
A - B

array([-3,  3,  2, 11])

In [ ]:
A * B

array([  4,  10,   3, -24])

In [ ]:
A / B

array([ 0.25      ,  2.5       ,  3.        , -2.66666667])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A + 4

array([ 5,  9,  7, 12])

In [ ]:
np.add(A, B)

array([5, 7, 4, 5])

In [ ]:
np.subtract(A, B)

array([-3,  3,  2, 11])

In [ ]:
np.multiply(A, B)

array([  4,  10,   3, -24])

In [ ]:
C = np.divide(A, B)

In [ ]:
C.reshape(2, -1)

array([[ 0.25      ,  2.5       ],
       [ 3.        , -2.66666667]])

In [ ]:
X = np.array([[2, 5], [-3, 2]])
Y = np.array([[1, 3], [3, -7]])

In [ ]:
X * Y

array([[  2,  15],
       [ -9, -14]])

In [ ]:
np.dot(X, Y)

array([[ 17, -29],
       [  3, -23]])

In [ ]:
Y.dot(X)

array([[-7, 11],
       [27,  1]])

In [ ]:
X @ Y

array([[ 17, -29],
       [  3, -23]])